### ISSUE TITLE
Privateform - can't approve a data deletion request

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/product-management#846]
> version: v1.0.8, production

When clicking on the "Approve a request" button, nothing happens:
![image](https://user-images.githubusercontent.com/7578400/181218650-4fad301d-01f7-43da-b240-54b88f0e85fb.png)

The following error is shown in the console:
```
Error: Promised response from onMessage listener went out of scope 5 [background.js:841:170](moz-extension://6f3ee04f-ede4-41b1-8302-6ddd5d448b55/dist/background.js)
ERROR UserNotInitializedError: Keys not initialized
    N https://form.blindnet.io/main.js:1
    getKeys https://form.blindnet.io/main.js:1
    Kt https://form.blindnet.io/main.js:1
    invoke https://form.blindnet.io/polyfills.js:1
    onInvoke https://form.blindnet.io/main.js:1
    invoke https://form.blindnet.io/polyfills.js:1
    run https://form.blindnet.io/polyfills.js:1
    F https://form.blindnet.io/polyfills.js:1
    invokeTask https://form.blindnet.io/polyfills.js:1
    onInvokeTask https://form.blindnet.io/main.js:1
    invokeTask https://form.blindnet.io/polyfills.js:1
    runTask https://form.blindnet.io/polyfills.js:1
    L https://form.blindnet.io/polyfills.js:1
    invokeTask https://form.blindnet.io/polyfills.js:1
    S https://form.blindnet.io/polyfills.js:1
    D https://form.blindnet.io/polyfills.js:1
[main.js:1:2861138](https://form.blindnet.io/main.js)
Error: Promised response from onMessage listener went out of scope 13 [background.js:841:170](moz-extension://6f3ee04f-ede4-41b1-8302-6ddd5d448b55/dist/background.js)
ERROR 
Object { headers: {…}, status: 400, statusText: "Bad Request", url: "https://api.form.blindnet.io/gdpr/request/051766b8-53fd-439d-ae63-ae6c55137ebd/approve", ok: false, name: "HttpErrorResponse", message: "Http failure response for https://api.form.blindnet.io/gdpr/request/051766b8-53fd-439d-ae63-ae6c55137ebd/approve: 400 Bad Request", error: "Data not deleted" }
[main.js:1:2861138](https://form.blindnet.io/main.js)
Error: Promised response from onMessage listener went out of scope
```

**Comment by Clementinev** [comment]
**On staging** : 
- Everything works well 

**On production**
- When confirming a delete request as a submitter, I get this message : 
<img width="1364" alt="Screenshot 2022-07-27 at 13 10 34" src="https://user-images.githubusercontent.com/89908145/181234092-7721e309-feac-44f6-a3ea-e3614f4355fd.png">

- Then the request still follows through

- Then when I try to approve the request as Data Consumer I get this error message : 
<img width="1380" alt="Screenshot 2022-07-27 at 13 15 19" src="https://user-images.githubusercontent.com/89908145/181234121-e46aa5b5-ef71-40ba-94a5-b1c07f9dbfe7.png">

**Comment by loncarb** [comment]
It seems that the problem is that this `AZURE_STORAGE_URL_CONNECTION_STRING` is missing from config on blindnet production, it is present for stage env

**Comment by m4rk055** [comment]
That was indeed the issue. Should be fixed now.

**Comment by noelmace** [comment]
@Clementinev please test this in production and close if fixed

**Comment by Clementinev** [comment]
- Works now well when confirming delete request as Submitter
**- Still doesn't work when approving delete request a Data Consumer**
<img width="1438" alt="Screenshot 2022-07-28 at 10 51 09" src="https://user-images.githubusercontent.com/89908145/181464222-27f7e3d0-a67a-4cbf-943b-a1edb3e304cc.png">

**Comment by loncarb** [comment]
@noelmace @Clementinev I would really need db access to debug this, read only will be enough for production

**Comment by loncarb** [comment]
When consumer approves delete request, we are first trying to delete files from azure and then removing form from our DB. What should we do deleting data from azure fails? Should we present error or just log it and delete form from our DB?

Problem with first approach is that on SDK we have one method for deleting one file and we have forms with multiple files. What can happen is that form has 4 files we try to delete them and first 3 pass but 4th fails then we don't have those files on azure but the form stays in our system. This is the problem that we are having now

**Comment by noelmace** [comment]
Any technical error should indeed lead to a clear, non technical error message for the end user.

All theses should also be implemented as ACID transactions for error management.

If any part of it fails, you should ideally:
- rollback the whole transaction
- send a notification to an error tracking system
- mention this in a clear user facing error message
- make sure the associated critical issue is solved in a minimum amount of time
- notify the end user the issue has been solved and they should retry the transaction (if in the backoffice only, we can handle this part)

**Comment by TheKinrar** [comment]
> I would really need db access to debug this, read only will be enough for production

@loncarb I'm on it, should be done today in the evening, I'll contact you on Slack about it :)

**Comment by loncarb** [comment]
@noelmace I agree that is ideal use case but SDK is not able to undo its action and it is deleting only one by one file, not the list

**Comment by noelmace** [comment]
I know this. This is something we (@blindnet-io/engineering) will address as part of the transition to a new data collection component (SDKs v2).

Globally, when I give an "ideal scenario", I really mean "ideal", as I'm fully aware some parts can't be addressed. I therefore expect people to propose alternative "realistic scenarios". Sorry for the lack of clarity.

**Comment by noelmace** [comment]
Following improvements to avoid this kind of critical bugs to happen will be discussed in another issue. Please, focus on fixing this one ASAP.

**Comment by Clementinev** [comment]
Just tested on production- still not working :( (here the request ID if needed : https://form.blindnet.io/gdpr/requests/delete/cf4fd6b0-81bf-43ae-872d-961e10fa7f48)
<img width="1440" alt="Screenshot 2022-08-04 at 12 13 47" src="https://user-images.githubusercontent.com/89908145/182823048-34a2f50a-be4d-43c8-b84b-4840dc4cd290.png">

**Comment by Clementinev** [comment]
Still doesn't work :( -> 16:44 , request ID : https://form.blindnet.io/gdpr/requests/delete/c9eaa11c-0e01-47a5-83d9-d021670128c4
